"""empty message

Revision ID: 5d9e318578ee
Revises: ca0ffc830ead
Create Date: 2022-10-28 14:58:15.342332

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '5d9e318578ee'
down_revision = 'ca0ffc830ead'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('email_captcha', sa.Column('verification_code', sa.String(length=10), nullable=False))
    op.drop_column('email_captcha', 'cpatcha')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('email_captcha', sa.Column('cpatcha', mysql.VARCHAR(length=10), nullable=False))
    op.drop_column('email_captcha', 'verification_code')
    # ### end Alembic commands ###
